### ISSUE TITLE
Show only Caller video both sides

### ISSUE THREAD

**Issue by Jagdeep-Sing** [webix-hub/webrtc-demo#3]
Hi, thanks for this awesome demo. can i modify this to show only caller(publisher) video both sides?
Means when i call someone then only my video will show to that user and my video will show to myself. is it possible?

**Comment by SebastianHurtado1** [comment]
I am having the same problem. Would love some clarification on this. Thanks.

**Comment by Jagdeep-Sing** [comment]
@juanhurtado4 I accomplish the task successfully by modifying the webrtc.js file
